spring:
  cloud:
    config:
      enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/assetflow-user-service-db
    username: sothrose
    password: sothrose
    driver-class-name: org.postgresql.Driver
