spring:
  application:
    name: assetflow-user-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}
server:
  port: 8081
  shutdown: graceful
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5